MAX_CLUSTER_SIZE : 50
MIN_CLUSTER_SIZE : 3
CLUSTER_TOLERANCE : 0.1

#params for removing ground plane
MAX_HEIGHT : 0.02
FLOOR_MAX_ANGLE : 5 #Invariant because of ransac plane fitting.

#params for ROS
TOPIC_TO_SUBSCRIBE_TO : "/rtabmap/cloud_map"

TOPIC_TO_PUBLISH : "/closest_cluster"
PLANAR_DIST_THRESHOLD : 0.05
PLANAR_MINIMUM_PERCENTAGE : 30

TRASH_CAN_CENTROID : [-0.7, -0.7, 0]
TRASH_CENTROIDS : [0,0]
WAYPOINTS: [0,0,0,-1,-1,0]
